/* 
pay_type :  10 本周免费  11 新手推荐
hero_type : 3:坦克  1:战士  4:刺客  2:法师   5:射手   6:辅助
*/
var heroArr = [{
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/105/105.jpg",
    "name": "廉颇",
    "pay_type": 10,
    "hero_type": 3,
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/106/106.jpg",
    "name": "小乔",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/107/107.jpg",
    "name": "赵云",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/108/108.jpg",
    "name": "墨子",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/109/109.jpg",
    "name": "妲己",
    "pay_type": 11,
    "hero_type": 2,
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/110/110.jpg",
    "name": "嬴政",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/111/111.jpg",
    "name": "孙尚香",
    "hero_type": 5,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/112/112.jpg",
    "name": "鲁班七号",
    "hero_type": 5,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/113/113.jpg",
    "name": "庄周",
    "pay_type": 10,
    "hero_type": 6,
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/114/114.jpg",
    "name": "刘禅",
    "hero_type": 6,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/115/115.jpg",
    "name": "高渐离",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/116/116.jpg",
    "name": "阿轲",
    "hero_type": 4,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/117/117.jpg",
    "name": "钟无艳",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/118/118.jpg",
    "name": "孙膑",
    "hero_type": 6,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/119/119.jpg",
    "name": "扁鹊",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/120/120.jpg",
    "name": "白起",
    "hero_type": 3,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/121/121.jpg",
    "name": "芈月",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/123/123.jpg",
    "name": "吕布",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/124/124.jpg",
    "name": "周瑜",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/126/126.jpg",
    "name": "夏侯惇",
    "hero_type": 3,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/127/127.jpg",
    "name": "甄姬",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/128/128.jpg",
    "name": "曹操",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/129/129.jpg",
    "name": "典韦",
    "pay_type": 10,
    "hero_type": 1,
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/130/130.jpg",
    "name": "宫本武藏",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/131/131.jpg",
    "name": "李白",
    "hero_type": 4,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/132/132.jpg",
    "name": "马可波罗",
    "hero_type": 5,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/133/133.jpg",
    "name": "狄仁杰",
    "pay_type": 11,
    "hero_type": 5,
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/134/134.jpg",
    "name": "达摩",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/135/135.jpg",
    "name": "项羽",
    "hero_type": 3,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/136/136.jpg",
    "name": "武则天",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/139/139.jpg",
    "name": "老夫子",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/140/140.jpg",
    "name": "关羽",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/141/141.jpg",
    "name": "貂蝉",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/142/142.jpg",
    "name": "安琪拉",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/144/144.jpg",
    "name": "程咬金",
    "hero_type": 3,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/146/146.jpg",
    "name": "露娜",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/148/148.jpg",
    "name": "姜子牙",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/149/149.jpg",
    "name": "刘邦",
    "hero_type": 3,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/150/150.jpg",
    "name": "韩信",
    "hero_type": 4,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/152/152.jpg",
    "name": "王昭君",
    "pay_type": 10,
    "hero_type": 2,
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/153/153.jpg",
    "name": "兰陵王",
    "pay_type": 10,
    "hero_type": 4,
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/154/154.jpg",
    "name": "花木兰",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/156/156.jpg",
    "name": "张良",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/157/157.jpg",
    "name": "不知火舞",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/162/162.jpg",
    "name": "娜可露露",
    "hero_type": 4,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/163/163.jpg",
    "name": "橘右京",
    "hero_type": 4,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/166/166.jpg",
    "name": "亚瑟",
    "pay_type": 11,
    "hero_type": 1,
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/167/167.jpg",
    "name": "孙悟空",
    "hero_type": 4,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/168/168.jpg",
    "name": "牛魔",
    "hero_type": 3,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/169/169.jpg",
    "name": "后羿",
    "hero_type": 5,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/170/170.jpg",
    "name": "刘备",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/171/171.jpg",
    "name": "张飞",
    "hero_type": 3,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/173/173.jpg",
    "name": "李元芳",
    "hero_type": 5,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/174/174.jpg",
    "name": "虞姬",
    "hero_type": 5,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/175/175.jpg",
    "name": "钟馗",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/177/177.jpg",
    "name": "成吉思汗",
    "hero_type": 5,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/178/178.jpg",
    "name": "杨戬",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/183/183.jpg",
    "name": "雅典娜",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/184/184.jpg",
    "name": "蔡文姬",
    "hero_type": 6,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/186/186.jpg",
    "name": "太乙真人",
    "hero_type": 6,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/180/180.jpg",
    "name": "哪吒",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/190/190.jpg",
    "name": "诸葛亮",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/192/192.jpg",
    "name": "黄忠",
    "hero_type": 5,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/191/191.jpg",
    "name": "大乔",
    "hero_type": 6,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/187/187.jpg",
    "name": "东皇太一",
    "hero_type": 3,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/182/182.jpg",
    "name": "干将莫邪",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/189/189.jpg",
    "name": "鬼谷子",
    "hero_type": 6,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/193/193.jpg",
    "name": "铠",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/196/196.jpg",
    "name": "百里守约",
    "hero_type": 5,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/195/195.jpg",
    "name": "百里玄策",
    "hero_type": 4,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/194/194.jpg",
    "name": "苏烈",
    "hero_type": 3,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/198/198.jpg",
    "name": "梦奇",
    "hero_type": 3,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/179/179.jpg",
    "name": "女娲",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/501/501.jpg",
    "name": "明世隐",
    "hero_type": 6,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/199/199.jpg",
    "name": "公孙离",
    "hero_type": 5,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/176/176.jpg",
    "name": "杨玉环",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/502/502.jpg",
    "name": "裴擒虎",
    "hero_type": 4,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/197/197.jpg",
    "name": "弈星",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/503/503.jpg",
    "name": "狂铁",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/504/504.jpg",
    "name": "米莱狄",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/125/125.jpg",
    "name": "元歌",
    "hero_type": 4,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/510/510.jpg",
    "name": "孙策",
    "hero_type": 3,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/137/137.jpg",
    "name": "司马懿",
    "hero_type": 4,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/509/509.jpg",
    "name": "盾山",
    "hero_type": 6,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/508/508.jpg",
    "name": "伽罗",
    "pay_type": 10,
    "hero_type": 5,
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/312/312.jpg",
    "name": "沈梦溪",
    "pay_type": 10,
    "hero_type": 2,
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/507/507.jpg",
    "name": "李信",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/513/513.jpg",
    "name": "上官婉儿",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/515/515.jpg",
    "name": "嫦娥",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/511/511.jpg",
    "name": "猪八戒",
    "hero_type": 3,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/529/529.jpg",
    "name": "盘古",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/505/505.jpg",
    "name": "瑶",
    "hero_type": 6,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/506/506.jpg",
    "name": "云中君",
    "hero_type": 4,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/522/522.jpg",
    "name": "曜",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/518/518.jpg",
    "name": "马超",
    "hero_type": 1,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/523/523.jpg",
    "name": "西施",
    "hero_type": 2,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/525/525.jpg",
    "name": "鲁班大师",
    "hero_type": 6,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/524/524.jpg",
    "name": "蒙犽",
    "hero_type": 5,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/531/531.jpg",
    "name": "镜",
    "hero_type": 4,
    "pay_type": 1
}, {
    "icon": "https://game.gtimg.cn/images/yxzj/img201606/heroimg/527/527.jpg",
    "name": "蒙恬",
    "hero_type": 1,
    "pay_type": 1
}];